# TCP network port
# - Default: 5252
#port = 5252
# TLS for HTTPS
# - Default: false
#tls = false
#cert = "/path/to/cert"
#key = "/path/to/key"
# Password protection
# - Default: false
#pass = false
# To get hash: "echo -n '<PASSWORD>' | sha512sum"
#hash = "SHA512 hash of password"
# To get random secret: "openssl rand -hex 32" 
#secret = "64-character secret"
# Other nodes viewable on frontend page
# - Defualt: []
# Please insert the IP addresses and ports of these nodes
# For example: ["192.168.1.1:5252", "192.168.1.60:4386"]
#nodes = []