# TCP network port
# - Default: 8088
#port = 8088
# TLS for HTTPS
# - Default: false
#tls = false
#cert = "/path/to/cert"
#key = "/path/to/key"
# Password protection
# - Default: false
#pass = false
# To get hash: "echo -n '<PASSWORD>' | sha512sum"
#hash = "SHA512 hash of password"
# To get random secret: "openssl rand -hex 32" 
#secret = "64-character secret"