# Config version
# DO NOT CHANGE
version = "1"

# Log level
# - Options: "off", "error", "warn", "info", "debug", "trace"
# - Default: "info"
#log_level = "info"

# TCP network port
# - Default: 5252
#port = 5252

# TLS for HTTPS
# - Default: false
#tls = false
#cert = "/path/to/cert"
#key = "/path/to/key"

# Password protection
# - Default: false
#pass = false
# To get hash: "echo -n '<PASSWORD>' | sha512sum"
#hash = "SHA512 hash of password"
# To get random secret: "openssl rand -hex 32" 
#secret = "64-character secret"
# Token expiry time in seconds
# - Default: 3600
#expiry = 3600

# Other nodes viewable on frontend page
# - Default: []
# Please insert the IP addresses/domains and ports of these nodes
# For example: ["example.com:5252", "192.168.1.60:4386"]
#nodes = []

# User to login to on the terminal
# Use "manual" to show a login prompt instead of auto-login
# - Default: "root"
#terminal_user = "root"

# Check for updates
# This will do 1 GitHub API call per day
# - Default: true
#update_check = true

# Preferred temperature unit
# - Options: fahrenheit, celsius
# - Default: celsius
#temp_unit = celsius
