[package]
name = "dietpi_dashboard"
version = "0.2.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
warp = {version = "0.3.1", features = ["compression"]}
tokio = { version = "1", features = ["full"] }
simple_logger = "1.13.0"
log = "0.4.14"
include_dir = "0.6.2"
lazy_static = "1.4.0"
futures = "0.3.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.67"
pty-process = "0.1.0"
heim = "0.0.11"

# Heim needs a patch to run on ARM64
[patch.crates-io]
heim = {git = "https://github.com/ravenclaw900/heim", branch = "patched"}

[profile.release]
lto = "fat"
panic = "abort"
codegen-units = 1
