[target.aarch64-unknown-linux-musl]
linker="aarch64-linux-gnu-gcc"

[target.arm-unknown-linux-musleabihf]
linker="/opt/rpi/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-musleabihf]
linker="arm-linux-gnueabihf-gcc"

[target.x86_64-unknown-linux-musl]
linker="x86_64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker="aarch64-linux-gnu-gcc"

[target.arm-unknown-linux-gnueabihf]
linker="/opt/rpi/arm-bcm2708/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"

[target.armv7-unknown-linux-gnueabihf]
linker="arm-linux-gnueabihf-gcc"

[target.x86_64-unknown-linux-gnu]
linker="x86_64-linux-gnu-gcc"
